### ISSUE TITLE
Display issue on some screens

### ISSUE THREAD

**Issue by Lucien-MG** [demixr/demixr-app#27] opened 2022-01-14 15:02 UTC
![Screenshot_20220114_155652_com demixr demixr_app](https://user-images.githubusercontent.com/45817540/149537052-70bc3d61-a2f2-484f-90bb-06f1f636058a.jpg)

**Comment by guillaume-merle** [comment] 2022-01-17 14:19
Duplicate of #9

**Closed as completed by guillaume-merle** 2022-01-17 14:19 UTC
Labels: bug
